export const FETCH_STATE_DATA="FETCH_STATE_DATA";
export const FETCH_STATE_SUCCESS="FETCH_STATE_SUCCESS"
export const FETCH_STATE_ERROR="FETCH_STATE_ERROR";
export const STATE_ADD = 'STATE_ADD';
export const STATE_VIEW = 'STATE_VIEW';
export const STATE_EDIT = 'STATE_EDIT';